### ISSUE TITLE
Arduino minimal doesn't fit into Atmega328P

### ISSUE THREAD

**Issue by DIY89** [jcassel/OctoPrint_SIOControl_Firmware#13]
Just tried to download the `https://github.com/jcassel/OctoPrint_SIOControl_Firmware/blob/main/SIO_Arduino_Minimal_Base/SIO_Arduino_Minimal_Base.ino` into Atmega328P (Ardunio Uno).

Build the firmware via PlatformIO in VSCode.
![SIO_Arduino_Minimal_Base - Visual Studio Code](https://github.com/jcassel/OctoPrint_SIOControl_Firmware/assets/18294295/02016c09-bb56-487b-9f37-ac286621980b)

Is there a way for compression during build process?
Otherwise i had to reduce the amount of IO-Ports (`IOSize`: 19 --> 11)

**Comment by jcassel** [comment]
Use the nano base.  It's optimized to use more program space to conserve RAM for run time.

**Comment by DIY89** [comment]
I'd optimized the `Serial.print("Test");` --> `Serial.print(F("Test"));`

This change fixed my issue with arduino uno
`Compiling .pio\build\uno\src\SIO_Arduino_Minimal_Base.ino.cpp.o`
`Linking .pio\build\uno\firmware.elf`
`Checking size .pio\build\uno\firmware.elf`
`Advanced Memory Usage is available via "PlatformIO Home > Project Inspect" `
`RAM:   [========= ]  92.8% (used 1900 bytes from 2048 bytes)`
`Flash: [====      ]  37.4% (used 12060 bytes from 32256 bytes)`
`Building .pio\build\uno\firmware.hex`

**Comment by jcassel** [comment]
That is the main difference in the nano version. I am planning on replacing the Arduino base with the nano version in the next update.

**Comment by jcassel** [comment]
I archived and rearranged the firmware versions available. There is now only one firmware path for Arduino and it is targeted at the 328p but will work on the larger MCUs as well.  So this will be the version maintained moving forward.  Should remove this confusion as to what firmware to use.
